### ISSUE TITLE
[question] how to see sources?

### ISSUE THREAD

**Issue by yosiat** [jhawthorn/vernier#103]
Hi,

I recently profiled my code using Vernier with the following setup:
```ruby
Vernier.profile(out: "...") {}
```
I used the `profile-viewer` gem to open the profiler output. However, when I click on a function in the viewer, the source code isn't annotated. Here’s a screenshot for reference:

![Screenshot](https://github.com/user-attachments/assets/8c57ae57-a7aa-4331-833f-4de95ac64990)

**Versions**:
- Ruby: 3.3.4 (with YJIT enabled, via RUBYOPT)
- profile-viewer: 0.0.2
- vernier: 1.2.1

Are there any specific instructions or additional steps I need to follow to get the source annotation working? Any guidance would be greatly appreciated!

Thank you.

**Comment by joshuay03** [comment]
Hey @yosiat apologies for the late reply. Unfortunately view source is a bit hit or miss (at least in my experience), but that's a known [issue](https://github.com/firefox-devtools/profiler/issues/3741) with the Firefox profiler itself (which https://vernier.prof/ and `profile-viewer` use under the hood). I'm closing since there's nothing we can really do on our end, but if you'd like to share an example profile we could try to dig into what's going on.
